CREATE TABLE LOG_STUDENTS (
	ID NUMBER PRIMARY KEY, 
	STUDENT_ID_OLD NUMBER NOT NULL,
	STUDENT_ID_NEW NUMBER NOT NULL,
	STUDENT_NAME_OLD )
	
CREATE TABLE STUDENTS (ID NUMBER PRIMARY KEY, NAME VARCHAR2(256) NOT NULL, GROUP_ID NUMBER NOT NULL);
