
--Create tables
	CREATE TABLE STUDENTS (ID NUMBER PRIMARY KEY, NAME VARCHAR2(256) NOT NULL, GROUP_ID NUMBER NOT NULL);

	CREATE TABLE GROUPS(ID NUMBER PRIMARY KEY, NAME VARCHAR2(64) NOT NULL, C_VAL NUMBER NOT NULL);

--Create triggers for autoincrementing unique ids
	CREATE SEQUENCE STUDENTS_ID_SEQ
		START WITH 1
		INCREMENT BY 1
		NOCACHE;

	CREATE SEQUENCE GROUPS_ID_SEQ
		START WITH 1
		INCREMENT BY 1
		NOCACHE;
	
--This triggers must provide following features:
--1. Using sequence for providing unique value when id of a new record is not given
--2. Check the uniqueness of the id when given on both insert and update operations
--3. Check the uniqueness of the GROUPS.NAME on both insert and update operations
--4. Control if value given to STUDENTS.GROUP_ID exists in GROUPS.ID on insert and update
	
	CREATE OR REPLACE TRIGGER STUDENTS_BEFORE_INSERT
	BEFORE INSERT ON STUDENTS
	FOR EACH ROW
	BEGIN 
		
	END;
	
	CREATE OR REPLACE TRIGGER STUDENTS_BEFORE_UPDATE
	BEFORE UPDATE ON STUDENTS
	FOR EACH ROW 
	BEGIN 
		
	END;
	
	CREATE OR REPLACE TRIGGER STUDENTS_AFTER_DELETE
	AFTER DELETE ON STUDENTS
	FOR EACH ROW 
	BEGIN 
		
	END;
	
	CREATE OR REPLACE TRIGGER GROUPS_BEFORE_INSERT
	BEFORE INSERT ON GROUPS
	FOR EACH ROW 
	BEGIN 
		
	END;
	
	CREATE OR REPLACE TRIGGER GROUPS_BEFORE_UPDATE
	BEFORE UPDATE ON GROUPS
	FOR EACH ROW 
	BEGIN 
		
	END;
	
	CREATE OR REPLACE TRIGGER GROUPS_BEFORE_DELETE
	BEFORE DELETE ON GROUPS
	FOR EACH ROW 
	BEGIN 
		
	END;
	
	
	