CREATE OR REPLACE PROCEDURE CREATE_GROUPS
IS 
BEGIN 
	DELETE FROM GROUPS;
	INSERT INTO GROUPS(NAME, C_VAL) 
	VALUES
	('FIRST', 0 ),
	('SECOND', 0),
	('THIRD', 0 );

END CREATE_GROUPS;

CREATE OR REPLACE PROCEDURE CREATE_STUDENTS
IS 
BEGIN 
	DELETE FROM STUDENTS;
	INSERT INTO STUDENTS(NAME, GROUP_ID)
	VALUES
	('IVANOV', (SELECT ID FROM GROUPS WHERE NAME = 'FIRST')),
	('PETROV', (SELECT ID FROM GROUPS WHERE NAME = 'SECOND')),
	('SIDOROV', (SELECT ID FROM GROUPS WHERE NAME = 'THIRD'));
END CREATE_STUDENTS;

CREATE OR REPLACE PROCEDURE TEST_CASCADE_DELETE_STUDENTS
IS
BEGIN
	DBMS_OUTPUT.PUT_LINE('Test CASCADE_DELETE_STUDENTS');
	
	DBMS_OUTPUT.PUT_LINE('STUDENTS before deletion');
	FOR ROW IN (SELECT * FROM STUDENTS) LOOP
		DBMS_OUTPUT.PUT_LINE(ROW.ID || ' ' || ROW.NAME || ' ' || ROW.GROUP_ID);
	END LOOP;
	
	DELETE FROM GROUPS;

	DBMS_OUTPUT.PUT_LINE('STUDENTS after deletion');
	FOR ROW IN (SELECT * FROM STUDENTS) LOOP
		DBMS_OUTPUT.PUT_LINE(ROW.ID || ' ' || ROW.NAME || ' ' || ROW.GROUP_ID);
	END LOOP;	
END;


CREATE OR REPLACE PROCEDURE TEST_CREATE_GROUP_WITH_EXISTNG_NAME
IS
BEGIN
	INSERT INTO GROUPS(NAME, C_VAL)
	VALUES
	('THIRD', 3);
END;

CREATE OR REPLACE PROCEDURE TEST_ALTER_GROUP_ID
IS
	MIN_GROUP_ID NUMBER := 0;
BEGIN
	SELECT MIN(GROUP_ID) INTO MIN_GROUP_ID FROM STUDENTS;
	UPDATE GROUPS SET ID = MIN_GROUP_ID - 1 WHERE ID = MIN_GROUP_ID;
END;


CREATE OR REPLACE PROCEDURE TEST_UNIQUE_AUTO_ID_GROUP
IS
BEGIN
	
	INSERT INTO 
END;

CREATE OR REPLACE PROCEDURE TEST_MOVE_STUDENT
IS
	MAX_GROUP_ID NUMBER := 0;
BEGIN
	SELECT MAX(GROUP_ID) INTO MAX_GROUP_ID FROM STUDENTS;
	UPDATE STUDENTS SET GROUP_ID = GROUP_ID-1 WHERE GROUP_ID = MAX_GROUP_ID;
END;



-- Pased
BEGIN CREATE_GROUPS(); END;

-- Pased
BEGIN CREATE_STUDENTS(); END;

-- Pased
BEGIN TEST_CASCADE_DELETE_STUDENTS(); END;

-- Pased
BEGIN
	TEST_CREATE_GROUP_WITH_EXISTNG_NAME();
END;

BEGIN TEST_ALTER_GROUP_ID; END;

-- Pased
BEGIN TEST_MOVE_STUDENT(); END;


DELETE FROM GROUPS;
SELECT * FROM GROUPS;
SELECT * FROM STUDENTS JOIN GROUPS ON STUDENTS.GROUP_ID = GROUPS.ID;



-- Check objects are created correctly
SELECT OBJECT_TYPE, OBJECT_NAME, STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME IN ('CREATE_GROUPS', 'CREATE_STUDENTS', 'TEST_CREATE_GROUP_WITH_EXISTNG_NAME',
	'TEST_CASCADE_DELETE_STUDENTS',
	'TEST_ALTER_GROUP_ID')
AND OBJECT_TYPE IN ('PROCEDURE')
ORDER BY OBJECT_TYPE, OBJECT_NAME;



INSERT INTO GROUPS(NAME, C_VAL) VALUES ('FOURTH', 2);

INSERT INTO STUDENTS(NAME, GROUP_ID) VALUES ('WHITE', 16);


-- Update students works correct
UPDATE STUDENTS SET ID = 7 WHERE NAME = 'WHITE';
UPDATE STUDENTS SET NAME = 'ROCK' WHERE NAME = 'STONE';
UPDATE STUDENTS SET GROUP_ID = 11 WHERE NAME = 'IVANOV';
UPDATE STUDENTS SET GROUP_ID = 1 WHERE NAME = 'WHITE';
UPDATE STUDENTS SET NAME = 'ROCK' WHERE NAME = 'WHITE';
UPDATE STUDENTS SET ID = 25 WHERE NAME = 'IVANOV';
UPDATE STUDENTS SET ID = 24 WHERE ID = 24;

-- Correct
UPDATE GROUPS SET NAME = 'THIRD' WHERE NAME = 'THRD';
UPDATE GROUPS SET C_VAL = 1 WHERE NAME = 'FIRST';
UPDATE GROUPS SET ID = 42, NAME = 'SECOND' WHERE ID = 42;

DELETE FROM GROUPS WHERE NAME = 'SECOND';
